apiVersion: v1
kind: Service
metadata:
  name: {{ include "quote-helm.fullname" . }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "quote-helm.name" . }}
